apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patches/app-image-pull.yaml
- path: patches/nginx-image-pull.yaml
- path: patches/mysql-image-pull.yaml

images:
- name: desafio-devops-app
  newName: us-central1-docker.pkg.dev/app1-349916/desafio/desafio-devops-app
  newTag: sha-d935513
- name: desafio-devops-db
  newName: us-central1-docker.pkg.dev/app1-349916/desafio/desafio-devops-db
  newTag: sha-d935513
- name: desafio-devops-nginx
  newName: us-central1-docker.pkg.dev/app1-349916/desafio/desafio-devops-nginx
  newTag: sha-d935513
